Source/UI/Zeta.WisdCar.Online/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Business;
using Zeta.WisdCar.Business.CustClubCardModule;
using Zeta.WisdCar.Business.CustClubCardModule.Impl;
using Zeta.WisdCar.Infrastructure;
using Zeta.WisdCar.Infrastructure.Helper;
using Zeta.WisdCar.Infrastructure.Log;
using Zeta.WisdCar.Model.Entity;
using Zeta.WisdCar.Model.VO;
using Zeta.WisdCar.Online.App_Start;
using Zeta.WisdCar.Online.Models;

namespace Zeta.WisdCar.Online.Controllers
{
    public class CustomerController : BasePageController
    {
        //
        // GET: /Customer/
        
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public JsonResult GetCustomers()
        {
            DatatablesResult<CustomerVO> result = new DatatablesResult<CustomerVO>();

            try
            {
                int start = NullHelper.Convert<int>(Request[Constants.PAGE_START], 0);
                int length = NullHelper.Convert<int>(Request[Constants.PAGE_LENGTH], 10);
                int draw = NullHelper.Convert<int>(Request[Constants.REQ_DRAW], 1);
                string sortOrder = NullHelper.Convert<string>(Request[Constants.SORT_ORDER], "desc");
                int sortIdx = NullHelper.Convert<int>(Request[Constants.SORT_IDX], 0);
                string columnKey = string.Format(Constants.SORT_NAME, sortIdx);
                string sortName = NullHelper.Convert<string>(Request[columnKey], "CustomerID");
                if(sortName=="CardFlagDesc"||sortName=="ClubCardDesc"||sortName=="CarDesc"||sortName=="Operation")
                {
                    sortName = "CustomerID";
                }
                string name = NullHelper.Convert<string>(Request["Name"], "");
                string icNo = NullHelper.Convert<string>(Request["ICNo"], "");
                string mobileNo = NullHelper.Convert<string>(Request["MobileNo"], "");
                int cardFlag = NullHelper.Convert<int>(Request["CardFlag"], -1);

                CustomerQueryEntity filter = new CustomerQueryEntity(){
                    Start = start,
                    Length = length,
                    SortOrder = sortOrder,
                    SortName = sortName,
                    Name = name,
                    ICNo = icNo,
                    MobileNo = mobileNo,
                    CardFlag = cardFlag
                };
                ICustomerMgm coustomer = new CustomerMgm();
                var list = coustomer.GetCustomers(filter);
                if (list == null)
                {
                    list = new List<CustomerVO>();
                }

                int recordsTotal = coustomer.GetRecordCount(filter);

                foreach (var item in list)
                {
                    item.DT_RowId = item.CustomerID.ToString();
                    if (item.CardFlag == 1)
                    {
                        item.CardFlagDesc = "<i class='fa fa-check fa-lg' style='color:green;'></i>";
                        item.ClubCardDesc = "<a href='javascript:void(0)' onclick='Customer.EditClubcard(" + item.DT_RowId + ")'><i class='fa fa-search'></i> 查看</a>";
                    }
                    else
                    {
                        item.CardFlagDesc = "<i class='fa fa-times fa-lg red' style='color:red;'></i>";
                        item.ClubCardDesc = "<a href='javascript:void(0)' onclick='Customer.AddCludcard(" + item.DT_RowId + ")'> <i class='fa fa-credit-card'></i> 开卡</a>";
                    }
                    item.CarDesc = "<a href='javascript:void(0)' onclick='Customer.EditCar(" + item.DT_RowId + ")'><i class='fa fa-search'></i> 查看</a>";
                    item.Operation = "<a href='javascript:void(0)' onclick='Customer.Edit("
                        + item.DT_RowId + ")'><i class='fa fa-pencil'></i> 编辑</a>  | <a href='javascript:void(0)' onclick='Customer.Del("
                        + item.DT_RowId + ")'><i class='fa fa-times'></i> 删除</a>";
                }

                result.draw = draw;
                result.recordsTotal = recordsTotal;
                result.recordsFiltered = recordsTotal;
                result.data = list;
            }
            catch (Exception ex)
            {
                result.data = new List<CustomerVO>();
                LogHandler.Error(ex.Message.ToString());
                result.error = ex.ToString();
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

      

        #region 客户管理
        /// <summary>
        /// 删除客户
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult DeleteCustomer(int id)
        {
            ICustomerMgm cusmgm = new CustomerMgm();
            ICarMgm carmgm = new CarMgm();
            ReturnedData data = new ReturnedData();
            try
            {
                cusmgm.DelCustomer(id);
                data.Message = "客户删除成功";
                data.Success = true;
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "客户删除失败";
                data.Error = ex.ToString();

            }

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 客户详细信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult CustomerDetails(int id)
        {
            var result = new CustomerAndCar();
            if (id != -1)
            {
                ICustomerMgm couMgm = new CustomerMgm();
                ICarMgm carMgm = new CarMgm();
                CustomerVO customer = couMgm.GetCustomerByID(id);
                List<CarVO> car = new List<CarVO>();
                if (customer != null)
                {
                    car = carMgm.GetCarsByCustID(customer.CustomerID);
                    result = GetcusAndcarObj(customer, car.FirstOrDefault());
                }

            }


            return View(result);
        }
        /// <summary>
        /// 客户修改提交
        /// </summary>
        /// <param name="customerandcar"></param>
        /// <returns></returns>
        public JsonResult CustomerEdiSub(CustomerAndCar customerandcar)
        {
            
            ICustomerMgm customerMgm = new CustomerMgm();

            CustomerVO customer = new CustomerVO()
            {
                CustomerID = customerandcar.Customerid,
                Name = customerandcar.Name,
                Sex = customerandcar.Sex,
                ICNo = customerandcar.ICNo,
                Birthday = customerandcar.Birthday,
                LastModifiedDate = DateTime.Now,
                CreatorID = Emp.UserName,
                LastModifierID = Emp.UserName,
                MobileNO = customerandcar.MobileNo
            };

            CarVO car = new CarVO()
            {
                CarID = customerandcar.Carid,
                CustomerID = customerandcar.Customerid,
                CarNo = customerandcar.Carno,
                Brand = customerandcar.Brand,
                CarModel = customerandcar.Carmodel,
                Capacity = customerandcar.Capacity,
                Color = customerandcar.Color,
                FrameNo = customerandcar.FrameNo,
                EngineNo = customerandcar.EngineNo,
                MaintainKM = customerandcar.Maintainkm,
                InsureDate = customerandcar.Insuredate,
                ASDate = customerandcar.Asdate,
                LastModifiedDate = DateTime.Now,
                CreatorID = Emp.UserName,
                LastModifierID = Emp.UserName,
            };

            ReturnedData data = new ReturnedData();
            try
            {
                var result = customerMgm.EditCustomer(customer, car);
                if(result)
                {
                    data.Message = "客户修改成功";
                    data.Success = true;
                }
                else
                {
                    data.Success = false;
                    data.Message = "客户修改失败";
                }
               
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "客户修改失败";
                data.Error = ex.ToString();

            }

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 添加客户提交
        /// </summary>
        /// <param name="cusandcar"></param>
        /// <returns></returns>
        public JsonResult AddCustomerSub(CustomerAndCar cusandcar)
        {
            
            ICustomerMgm customerMgm = new CustomerMgm();
            ICarMgm carMgm = new CarMgm();
            CustomerVO customer = new CustomerVO()
            {

                Name = cusandcar.Name,
                Sex = cusandcar.Sex,
                ICNo = cusandcar.ICNo,
                Birthday = cusandcar.Birthday,
                MobileNO = cusandcar.MobileNo,
                CreatorID = Emp.UserName,
                LastModifierID = Emp.UserName,
                CreatedDate = DateTime.Now,
                LastModifiedDate = DateTime.Now,
            };

            CarVO car = new CarVO()
            {

                CarNo = cusandcar.Carno,
                Brand = cusandcar.Brand,
                CarModel = cusandcar.Carmodel,
                Capacity = cusandcar.Capacity,
                Color = cusandcar.Color,
                FrameNo = cusandcar.FrameNo,
                EngineNo = cusandcar.EngineNo,
                MaintainKM = cusandcar.Maintainkm,
                InsureDate = cusandcar.Insuredate,
                ASDate = cusandcar.Asdate,
                CreatorID = Emp.UserName,
                LastModifierID = Emp.UserName,
                CreatedDate = DateTime.Now,
                LastModifiedDate = DateTime.Now,

Source/UI/Zeta.WisdCar.Online/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Infrastructure.Log;

namespace Zeta.WisdCar.Online.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /TestLayout/
        public ActionResult Index()
        {
            Business.BizMocker.MockLog4Net();

            return View();
        }
    }
}

Source/UI/Zeta.WisdCar.Online/Views/ClubCard/ChangeCardNo.cshtml
@model Zeta.WisdCar.Model.VO.ClubCardVO

<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            补办会员卡 <small>Go through the membership card</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="@Url.Action("Index", "Dashboard")">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    会员管理
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    补办会员卡
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>补办会员卡
        </div>
    </div>


    <div class="portlet-body">
        <!--页头 开始 -->
        <div class="portlet box" style="border-bottom:1px solid #bde9f1;">
            <div class="portlet-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="txtQyName">客户姓名:</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.CustName, new { @class = "form-control", @readonley = true })

                        </div>
                        <label class="col-md-2 control-label" for="txtQyCardNo">会员卡号:</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.ClubCardNo, new { @class = "form-control", @readonley = true })
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!--页头 开始 -->
        <!--修改密码 开始 -->

        <div class="portlet box" style="margin-bottom:10px; border:1px solid #bde9f1;">
            <div class="portlet-body">
                <div class="form-body">
                    <form action="#" id="form_sample_1" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-md-2 control-label">新会员卡号:  <span class="required"> * </span></label>
                            <div class="col-md-4">
                                <div class="input-icon right">
                                    <i class="fa"></i>
                                    <input name="CardNo" id="CardNo" type="text" class="form-control" />
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <a id="btnQy" href="javacript:void(0);" onclick="subForm(); return false;" class="btn btn-md blue"> 确定 </a>
                            </div>
                            <div class="col-md-4"></div>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <!--修改密码 结束 -->

    </div>

</div>
<!-- END PAGE CONTENT-->
@section scripts{
    <script>
        function subForm() {
            var cardno = $('#CardNo').val();
            if (!cardno)
            {
                alert('请输入新会员卡号');
                return;
            }
            var id = getQueryString("id");
            $.ajax({
                "type": "post",
                "url": "@Url.Action("ChangeCardNoSub", "ClubCard")",
                "data": { id: id, CardNo: cardno },
                  "dataType": "json",
                  "ansyc": true,
                  "cache": false,
                  "success": function (re) {
                      if (re.Success)
                      {
                          alert(re.Message);
                      } else {
                          alert(re.Message);
                      }
                  },
                  "error": function () {
                      alert(re.error);
                  }
        });
        }
        function getQueryString(name) {
            var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
            var r = window.location.search.substr(1).match(reg);
            if (r != null) return unescape(r[2]); return null;
        }
        $(function () {

        });
    </script>
}

Source/UI/Zeta.WisdCar.Online/Views/ClubCard/Index.cshtml
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            会员卡管理 <small>Clubcard Management</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="@Url.Action("Index", "Dashboard")">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    会员管理
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    会员卡管理
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->


<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>会员卡管理
        </div>
        <div class="tools">
        </div>
        <a href="@Url.Action("ClubcardDetails","ClubCard")?id=-1" class="btn btn-xs blue" style="float:right; ">
            <i class="fa fa-plus"></i> 新增
        </a>
    </div>


    <div class="portlet-body">

        <div class="portlet box" style="margin-bottom:10px; border:1px solid #bde9f1;">
            <div class="portlet-body">
                <form class="form-horizontal" id="frmQy">
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="txtQyCardNo">会员卡号</label>
                        <div class="col-md-2">
                            <input type="text" id="txtQyCardNo" name="ClubcardNO" class="form-control" placeholder="">
                        </div>
                        <label class="col-md-2 control-label" for="ddlCardType">会员卡类型</label>
                        <div class="col-md-2">
                            @*<%=Html.DropDownList("list")%>*@
                            @Html.DropDownList("ClubcardType", null, new { @class = "form-control input-md" })
                            @*<select id="ddlCardType" name="ClubcardType" class="form-control input-md">
                                <option value="-1">-请选择-</option>
                                <option value="2">白金卡</option>
                                <option value="1">金卡</option>
                            </select>*@
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="txtQyName">客户姓名</label>
                        <div class="col-md-2">
                            <input type="text" id="txtQyName" name="CustomerName" class="form-control" placeholder="">
                        </div>
                        <label class="col-md-2 control-label" for="txtQyMobileNo">客户手机号</label>
                        <div class="col-md-2">
                            <input type="text" id="txtQyMobileNo" name="MobileNo" class="form-control" placeholder="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="ddlCardState">会员卡状态</label>
                        <div class="col-md-2">
                            <select id="ddlCardState" name="CardStatus" class="form-control input-md">
                                <option value="-1">-请选择-</option>
                                <option value="0">开卡</option>
                                <option value="1">挂失</option>
                                <option value="2">冻结</option>
                                <option value="3">注销</option>
                                <option value="4">过期</option>
                            </select>
                        </div>
                        <label class="col-md-2 control-label" for="txtQyCardDoor">开卡门店</label>
                        <div class="col-md-2">
                            <input type="text" id="txtQyCardDoor" name="SaleCardStore" class="form-control" placeholder="">
                        </div>
                        <div class="col-md-2">

                        </div>
                        <div class="col-md-2">
                            <a id="btnQy" href="javacript:void(0);" onclick="searchList(); return false;" class="btn btn-md blue">
                                <i class="fa fa-search"></i> 查询
                            </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>

        <table id="tblClubCard" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>会员卡号</th>
                    <th>会员卡类型</th>
                    <th>客户姓名</th>
                    <th>手机号码</th>
                    <th>会员卡状态</th>
                    <th>开卡门店</th>
                    <th style="text-align:center;">操作</th>
                </tr>
            </thead>

            <tbody>
                @*<tr>
                    <td>00001</td>
                    <td>白金卡</td>
                    <td> 张三</td>
                    <td>15865424972</td>
                    <td id="ajax-demo" data-toggle="modal"><a href=""><i class="fa fa-search blue"></i> 已开卡</a></td>
                    <td data-target="#static" data-toggle="modal"><a href=""> 门店一</a></td>
                    <td style="text-align:center;">
                        <div class="btn-group">
                            <button class="btn blue dropdown-toggle" type="button" data-toggle="dropdown">
                                操作 <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href="#">查看</a></li>
                                <li><a href="#">套餐余额</a></li>
                                <li><a href="#">修改密码</a></li>
                                <li class="divider"></li>
                                <li><a href="#">挂失/注销</a></li>
                                <li><a href="">补办会员卡</a></li>
                                <li><a href="">套餐充值</a></li> 
                                <li><a href="">会员消费</a></li>
                                <li><a href="">已完结套餐查询</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>*@


            </tbody>
        </table>

       

    </div>
</div>
		
<!-- END EXAMPLE TABLE PORTLET-->
<!-- END PAGE CONTENT-->
<!-- END PAGE CONTENT-->
<!-- END PAGE CONTENT-->
@section styles{
    <link href="@Url.Content("~/assets/plugins/datatables/css/jquery.dataTables.min.css")" rel="stylesheet" />
}

@section scripts{
    <script src="@Url.Content("~/assets/plugins/datatables/js/jquery.dataTables.min.js")" type="text/javascript"></script>
    <script>
        var type;
        var ClubCard = function () {
            var onPageLoad = function () {
                initClubCardTable();
            };

            var initClubCardTable = function (a) {
                var table = $("#tblClubCard");
                var customerTable = $("#tblClubCard").DataTable({
                    "processing": true,
                    "serverSide": true,
                    "ajax": {
                        "type": "post",
                        "url": "@Url.Action("GetCludCardList", "ClubCard")",
                        "dataSrc": "data",
                        "data": function (d) {
                            var formData = $("#frmQy").serializeArray();
                            formData.forEach(function (e) {
                                d[e.name] = e.value;
                            });
                        },
                        "cache": false
                    },
                    "columns": [
                        { "data": "ClubCardNo" },
                        { "data": "ClubCardTypeName" },
                        { "data": "CustName" },
                        { "data": "MobileNo" },
                        { "data": "CardStatusDesc" },
                        { "data": "OpenCardStore" },
                        { "data": "Operation" }
                    ],
                    "initComplete": function (setting, json) {
                        $("#tblClubCard_filter").html("");
                    },
                    "scrollX": true,
                    "paging": true,
                    "ordering": true,
                    "info": true,
                    "retrieve": true,    //重复初始化，索引到同一个Datatables实例
                    //"pagingType": "full_numbers",
                    "pageLength": 10,
                    "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                    "language": {
                        "emptyTable": "没有数据",
                        "loadingRecords": "加载中...",
                        "processing": "查询中...",
                        "search": "查询: ",
                        "lengthMenu": "显示_MENU_条",
                        "zeroRecords": "没有数据",
                        "paginate": {
                            "previous": "上一页",
                            "next": "下一页",
                            "first": "第一页",
                            "last": "最后一页"
                        },
                        "info": "显示_START_-_END_，共_TOTAL_条记录",
                        "infoEmpty": "0条记录",
                        "infoFiltered": "(查询前有_MAX_条记录)"
                    }
                });

                $("#tblClubCard tbody").on("click", "tr", function () {

                    if ($(this).hasClass('selected')) {
                        $(this).removeClass('selected');
                    }
                    else {
                        customerTable.$('tr.selected').removeClass('selected');
                        $(this).addClass('selected');
                    }
                });

                $("#tblClubCard_filter input").addClass("form-control input-medium input-inline");
                $("#tblClubCard_length select").addClass("form-control input-xsmall input-inline");

            };

            return {
                Init: function (a) {
                    $("#sidebar_menu_cust_card").addClass("active");
                    $("#sidebar_menu_card").addClass("active");
                    App.blockUI({ boxed: true });
                    if (!a)
                    {
                        onPageLoad();
                    }
                    else
                    {
                        onreload();
                    }
                    window.setTimeout(function () {
                        App.unblockUI();
                    }, 1000);
                },

                Del: function (id) {
                    $.ajax({
                        "type": "post",
                        "url": "@Url.Action("DeleteCustomer", "Customer")",
                        "dataType": "json",
                        "data":{id:id},
                        "async":true,
                        "cache": false,
                        "success": function (re) {
                            if (re.Success)
                            {
                                alert(re.Message);
                                start = $("#tblClubCard").dataTable().fnSettings()._iDisplayStart;
                                total = $("#tblClubCard").dataTable().fnSettings().fnRecordsDisplay();
                                //window.location.reload();
                                if ((total - start) == 1) {
                                    if (start > 0) {
                                        $("#tblClubCard").dataTable().fnPageChange('previous', true);
                                        closedilog();
                                    }
                                }
                                $("#tblClubCard").dataTable().fnDraw();
                            }
                            else
                            {
                                alert(re.Message);
                                closedilog();
                            }
                        },
                        "error": function () {
                            alert(re.Error);
                        }
                });
                },
                Operation: function (id)
                {
                    
                },
                Edit: function (id) {
                   

                },
                //查看
                EditClubcard: function (id) {
                  

                },
                //查看汽车
                EditCar: function (id) {
                  

                },
                //开卡
                AddCludcard: function (id) {
                  

                }
            };
        }();
      


        $(function () {
            ClubCard.Init();
        });

        function searchList() {
            try {
                $('#tblClubCard').dataTable().fnClearTable();
            }
            catch (ex) {
            }
            finally {
                ClubCard.Init();
            }

        }

      
       
    
    </script>
}