Source/UI/Zeta.WisdCar.Online/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Zeta.WisdCar.Model.PO;

namespace Zeta.WisdCar.Online.Models
{
    public class EmployeeViewModel
    {
        string username;
        string userpassword;
        int userid;
        int storeid;
        string storename;
        string name;
        public string Name
        {
            set { name = value; }
            get { return name; }
        }

        public string UserName
        {
            get { return username; }
            set { username = value; }
        }

        public string UserPassword 
        {
            get { return userpassword; }
            set { userpassword = value; }
        }
        public int UserId
        {
            get { return userid; }
            set { userid = value; }
        }
        public int StoreId
        {
            get { return storeid; }
            set { storeid = value; }
        }
        public string StroeName
        {
            get { return storename; }
            set { storename = value; }
        }
    }
}

Source/UI/Zeta.WisdCar.Online/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Infrastructure.Log;

namespace Zeta.WisdCar.Online.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /TestLayout/
        public ActionResult Index()
        {
            Business.BizMocker.MockLog4Net();

            return View();
        }
    }
}

Source/UI/Zeta.WisdCar.Online/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Business.BasicDataModule;
using Zeta.WisdCar.Model.PO;
using Zeta.WisdCar.Online.App_Start;
using Zeta.WisdCar.Online.Models;

namespace Zeta.WisdCar.Online.Controllers
{
    public class EmployeeController : BasePageController
    {
        //
        // GET: /Employee/
        public ActionResult Index()
        {
            return View();
        }
        [LoginCheckFilterAttribute(IsCheck = false)]
        public ActionResult Login()
        {
            return View();
        }
        [LoginCheckFilterAttribute(IsCheck = false)]
        [HttpPost]
        public JsonResult LoginSub(EmployeePO emp)
        {
            IEmployeeMgm empMgm = new EmployeeMgm();

            ReturnedData data = new ReturnedData();
            EmployeePO empdb = new EmployeePO();
            try
            {
                string spwd;
                var result = empMgm.Login(emp,out empdb);
                if(result==null)
                {
                    data.Success = true;
                    if(empdb!=null)
                    {
                        SetLoginUser(empdb);
                    }
                    
                }
                else
                {
                    data.Success = false;
                    
                }
                data.Message = result;
                
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "出现错误，请联系维护人员";
                data.Error = ex.ToString();

            }
            return Json(data, JsonRequestBehavior.AllowGet);
           

            
        }
        
        public ActionResult ResetPassword()
        { 
            return View();
        }
        public JsonResult ResetPwdsub(string oldpwd,string password)
        {
            IEmployeeMgm empMgm = new EmployeeMgm();

            ReturnedData data = new ReturnedData();
            try
            {
                var emp = Session["loginUser"] as EmployeeViewModel;
                bool boolresult;
                string spwd;
                var emppo = new EmployeePO() 
                {
                    EmployeeID=emp.UserId,
                    EmployeeNo=emp.UserName,
                    Reserved1=emp.UserPassword,
                    StoreID=emp.StoreId,
                    Name=emp.Name
                };
                var result = empMgm.ChangePassword(emppo,oldpwd,password,out boolresult,out spwd);
                data.Success = boolresult;
                data.Message = result;
                if (boolresult)
                {
                    emppo.Reserved1 = spwd;
                    SetLoginUser(emppo);
                }
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "出现错误，请联系维护人员";
                data.Error = ex.ToString();

            }
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SinOut()
        {
            Session["loginUser"] = null;
            return RedirectToAction("Login");
        }
	}
}

Source/UI/Zeta.WisdCar.Online/Views/Employee/Index.cshtml
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            员工管理 <small>Employee Management</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="@Url.Action("Index", "Dashboard")">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    公司管理
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    员工管理
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        Page content goes here
    </div>
</div>
<!-- END PAGE CONTENT-->
@section scripts{
    <script>
        var Employee = function () {
            var onPageLoad = function () {

            };

            return {
                Init: function () {
                    $("#sidebar_menu_company").addClass("active");
                    $("#sidebar_menu_employee").addClass("active");
                    App.blockUI({ boxed: true });
                    onPageLoad();
                    window.setTimeout(function () {
                        App.unblockUI();
                    }, 1000);
                }
            };
        }();

        $(function () {
            Employee.Init();
        });
    </script>
}

Source/UI/Zeta.WisdCar.Online/Views/Employee/Login.cshtml
@model Zeta.WisdCar.Model.PO.EmployeePO

@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en" class="no-js">

<head>
    @*@Styles.Render("~/global/css")
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN THEME STYLES -->
    @Styles.Render("~/theme/css")*@
    <meta charset="utf-8">
    <title>智慧汽车商家平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- 新增的loginCSS -->
    <link rel="stylesheet" href="~/assets/css/pages/reset.css">
    <link rel="stylesheet" href="~/assets/css/pages/supersized.css">
    <link rel="stylesheet" href="~/assets/css/pages/style.css">

    <!-- 新增的loginJS -->
    <script src="~/assets/plugins/login/js/jquery-1.8.2.min.js"></script>

    <script src="~/assets/plugins/login/js/supersized.3.2.7.min.js"></script>
    <script src="~/assets/plugins/login/js/supersized-init.js"></script>
    <script src="~/assets/plugins/login/js/scripts.js"></script>
    <script type="text/javascript">
        function formsubmit() {
            var uname = $('#username').val();
            var pwd = $('#pwd').val();
            if(!uname.trim())
            {
                alert("请输入用户名");
                return;
            }
            if(!pwd)
            {
                alert("请输入密码");
                return;
            }
            $.ajax({
                "type": "post",
                "url": "@Url.Action("Loginsub", "Employee")",
                        "dataType": "json",
                        "data": { EmployeeNo: uname,Reserved1:pwd },
                        "async":true,
                        "cache": false,
                        "success": function (re) {
                            if (re.Success)
                            {
                                window.location = "@Url.Action("Index","Dashboard")";
                            }
                            else
                            {
                                alert(re.Message);
                            }
                        }, 
                        "error": function () {
                            alert(re.Error);
                        }
            });
        }
    </script>
</head>

<body>

    <div class="page-container">
        <h1>智慧汽车商家平台</h1>
        <form action="" method="post">
            <input type="text" name="username" id="username" class="username" placeholder="用户名">
            <input type="password" name="password" id="pwd" class="password" placeholder="密码">
            <input type="hidden" name="openid" value="">
            <button type="button" onclick="formsubmit()">登 录</button>
            <div class="error"><span>+</span></div>

        </form>
       
    </div>
    <div class="copyright" style="font-size:14px; color:#fff; margin-top:10px;">
        2015 © 智慧汽车商家平台 1.0版本
    </div>
   

</body>

</html>

Source/UI/Zeta.WisdCar.Online/Views/Employee/ResetPassword.cshtml
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            员工管理 <small>Employee Management</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="@Url.Action("Index", "Dashboard")">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    帐号管理
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    密码管理
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        
            <!-- 需要用的 开始-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-globe"></i>重置密码
                    </div>
                </div>


                <div class="portlet-body">
                   
                    <!--修改密码 开始 -->

                    <div class="portlet box" style="margin-bottom:10px; border:1px solid #bde9f1;">
                        <div class="portlet-body">
                            <form action="#" id="form_sample_1" class="form-horizontal">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">旧密码:  <span class="required"> * </span> </label>
                                        <div class="col-md-4">
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input name="oldpwd" id="oldpwd" type="password" class="form-control" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">新密码:  <span class="required"> * </span> </label>
                                        <div class="col-md-4">
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input name="password" id="password" type="password" class="form-control" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">确认新密码:  <span class="required"> * </span> </label>
                                        <div class="col-md-4">
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input name="newpwd" id="newpwd" type="password" class="form-control" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-4 control-label"></label>
                                        <div class="col-md-4">
                                            <a id="btnQy" href="javacript:void(0);" onclick="resetPwd()" class="btn btn-md blue"> 确定 </a>
                                        </div>
                                        <div class="col-md-4"></div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
        
    </div>
</div>
<!-- END PAGE CONTENT-->
@section scripts{
    <script>
        var ConsumeLog = function () {
            var onPageLoad = function () {

            };

            return {
                Init: function () {
                    $("#sidebar_menu_recharge_consume").addClass("active");
                    $("#sidebar_menu_consume_log").addClass("active");
                    App.blockUI({ boxed: true });
                    onPageLoad();
                    window.setTimeout(function () {
                        App.unblockUI();
                    }, 1000);
                }
            };
        }();

        $(function () {
            //ConsumeLog.Init();
        });
        function resetPwd()
        {
            var oldpwd = $('#oldpwd').val();
            var password = $('#password').val();
            var newpwd = $('#newpwd').val();
            if (!oldpwd) {
                alert("请输入旧密码");
                return;
            }
            else if (!password) {
                alert("请输入新密码");
                return;
            } else if (!newpwd) {
                alert("请再次输入新密码");
                return;
            }
            if (password !== newpwd)
            {
                alert("两次输入密码不一致，请重新输入");
                return;
            }

            $.ajax({
                "type": "post",
                "url": "@Url.Action("ResetPwdsub","Employee")",
                "dataType": "json",
                "data": {oldpwd:oldpwd,password:password},
                "async": true,
                "cache": false,
                "success": function (re) {
                    if (re.Success) {
                        alert(re.Message);
                    }
                    else {
                        alert(re.Message);
                    }
                },
                "error": function () {
                    alert(re.Error);
                }
            });
        }
    </script>
}