Source/UI/Zeta.WisdCar.Online/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Infrastructure.Log;

namespace Zeta.WisdCar.Online.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /TestLayout/
        public ActionResult Index()
        {
            Business.BizMocker.MockLog4Net();

            return View();
        }
    }
}

Source/UI/Zeta.WisdCar.Online/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Business;
using Zeta.WisdCar.Business.MarktingPlanModule;
using Zeta.WisdCar.Infrastructure;
using Zeta.WisdCar.Infrastructure.Helper;
using Zeta.WisdCar.Infrastructure.Log;
using Zeta.WisdCar.Model.VO;
using Zeta.WisdCar.Online.App_Start;
using Zeta.WisdCar.Online.Models;

namespace Zeta.WisdCar.Online.Controllers
{
    public class PackageController : BasePageController
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllPackages()
        {
            List<PackageVO> result = new List<PackageVO>();

            try
            {
                PackageMgm pkgMgm = new PackageMgm();
                //BizMocker mocker = new BizMocker();
                result = pkgMgm.GetAllPackages();
                foreach (var item in result)
                {
                    item.DT_RowId = item.PackageID.ToString();
                    item.Operation = "<a href='javascript:void(0)' onclick='Package.Edit("
                        + item.DT_RowId + ")'><i class='fa fa-pencil'></i> 编辑</a>  | <a href='javascript:void(0)' onclick='Package.Del("
                        + item.DT_RowId + ")'><i class='fa fa-times'></i> 删除</a>";
                    item.TotalPriceDesc = item.TotalPrice.ToString() + " 元";
                    item.DetailOpt = "<a href='javascript:void(0)' onclick=\"Package.Detail("
                        + item.DT_RowId + ", '" + PageValidateHelper.FilterParams(item.PackageName) + "')\"><i class='fa fa-search'></i> 查看</a>";
                }
            }
            catch (Exception ex)
            {
                LogHandler.Error(ex.Message.ToString());
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DetailItems()
        {
            try
            {
                string pkgName = NullHelper.Convert<string>(Request["pkgName"], "");
                int pkgID = NullHelper.Convert<int>(Request["id"], 0);
                string v = HttpUtility.UrlDecode(pkgName);
                ViewBag.PkgName = v;
                ViewBag.PkgID = pkgID;
            }
            catch (Exception ex)
            {
                LogHandler.Error(ex.Message.ToString());
            }
            return View();
        }
        //套餐基本信息页
        public ActionResult DetailPkg()
        {
           
            try
            {
                int pkgId = NullHelper.Convert<int>(Request["id"], -1);
                if(pkgId>0)
                {
                    PackageMgm pkgMgm = new PackageMgm();
                    var pkg = pkgMgm.GetPackageByID(pkgId);
                    ViewBag.pkgName = pkg.PackageName;
                    ViewBag.pkgPrice = pkg.TotalPrice;
                    ViewBag.pkgId = pkg.PackageID;
                }
                else
                {
                    ViewBag.pkgName = "";
                    ViewBag.pkgPrice = "";
                    ViewBag.pkgId = -1;
                }
            }
            catch(Exception ex)
            {
                LogHandler.Error(ex.Message.ToString());
            }
            return View();
        }
        //添加/修改 套餐基本信息
        public JsonResult SubPkg()
        {
            ReturnedData data = new ReturnedData();
            try
            {
                int id = NullHelper.Convert<int>(Request["id"], -1);
                string pkgName = NullHelper.Convert<string>(Request["pkgName"], "");
                decimal pkgPrice = NullHelper.Convert<decimal>(Request["pkgPrice"], 0M);

                if (id == -1)
                {
                    data = AddPkg(pkgName, pkgPrice);
                }
                else
                {
                    data = EditePkg(id, pkgName, pkgPrice);
                }
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "出现错误，请联系维护人员";
                data.Error = ex.ToString();
                LogHandler.Error(ex.Message.ToString());
            }
            return Json(data,JsonRequestBehavior.AllowGet);
        }
        private ReturnedData AddPkg(string pkgName,decimal pkgPrice)
        {
            ReturnedData data = new ReturnedData();
            PackageMgm pkgMgm = new PackageMgm();
            PackageVO pkg = new PackageVO();
            pkg.PackageName = pkgName;
            pkg.TotalPrice = pkgPrice;
            pkg.CreatedDate = DateTime.Now;
            pkg.CreatorID = Emp.UserName;
            pkg.LastModifiedDate = DateTime.Now;
            pkg.LastModifierID = Emp.UserName;
            try
            {
                data.Data = pkgMgm.AddPackage(pkg);
                data.Success = true;
                data.Message = "套餐基本信息添加成功";
                LogHandler.Info("用户：" + Emp.UserName + "于 "+pkg.CreatedDate.ToString()+" 添加套餐基本信息，项目名：" + pkgName);
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "套餐基本信息添加失败";
                data.Error = ex.ToString();
                LogHandler.Error("套餐基本信息添加错误：" + ex.Message.ToString());
            }
            return data;
        }
        private ReturnedData EditePkg(int id,string pkgName,decimal pkgPrice)
        {
            ReturnedData data = new ReturnedData();
            PackageMgm pkgMgm = new PackageMgm();
           
            try
            {
                var pkg = pkgMgm.GetPackageByID(id);
                if(pkg.PackageID>0)
                {
                    pkg.PackageName = pkgName;
                    pkg.TotalPrice = pkgPrice;
                    pkg.LastModifiedDate = DateTime.Now;
                    pkg.LastModifierID = Emp.UserName;
                    pkgMgm.EditPackage(pkg);
                    data.Success = true;
                    data.Message = "套餐基本信息修改成功";
                    LogHandler.Info("用户：" + Emp.UserName + "于 " + pkg.CreatedDate.ToString() + " 修改套餐基本信息，项目名：" + pkgName);
                }
                else
                {
                    data.Success = false;
                    data.Message = "所选套餐项目不存在,请刷新网页后重试";
                }
               
            }
            catch(Exception ex)
            {
                data.Success = false;
                data.Message = "套餐基本信息修改失败";
                LogHandler.Error("套餐基本信息修改错误：" + ex.Message.ToString());
            }
            return data;
        }
        public JsonResult DeletePackage(int id)
        {
            ReturnedData data = new ReturnedData();
            PackageMgm pkgMgm = new PackageMgm();
            try
            {
                pkgMgm.DelPackage(id);
                data.Success = true;
                data.Message = "套餐基本信息删除成功";
                LogHandler.Info("用户：" + Emp.UserName + "于 " + DateTime.Now.ToString() + " 删除套餐基本信息，项目id：" + id);
            }
            catch(Exception ex)
            {
                data.Success = false;
                data.Message = "套餐基础信息删除失败，请先删除该套餐下的消费项目后再尝试";
                data.Error = ex.ToString();
                LogHandler.Error("套餐基本信息删除错误：" + ex.Message.ToString());
            }
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetItemsByPkgId()
        {
            List<PkgItemVO> result = new List<PkgItemVO>();

            try
            {
                int id = NullHelper.Convert<int>(Request["id"], -1);
                //var mocker = new BizMocker();
                PkgItemsMgm pkgItemMgm = new PkgItemsMgm();
                result = pkgItemMgm.GetItemsByPkgID(id);
                foreach (var item in result)
                {
                    item.DT_RowId = item.PackageItemID.ToString();
                    item.Operation = "<a href='javascript:void(0)' onclick=\"PackageItems.Del("
                        + item.DT_RowId + ",'" + PageValidateHelper.FilterParams(item.ItemName) + "')\"><i class='fa fa-times'></i> 删除</a>";
                }
            }
            catch (Exception ex)
            {
                LogHandler.Error(ex.Message.ToString());
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PkgItemDetail()
        {
            string pkgName = NullHelper.Convert<string>(Request["pkgName"], "");
            int pkgID = NullHelper.Convert<int>(Request["id"], 0);
            ViewBag.PkgName = pkgName;
            ViewBag.PkgID = pkgID;
            ViewData["ConItem"] = GetddlList(DDLlist.PkgItem, false, null, null, pkgID);
            return View();
        }
        public JsonResult AddPkgItem()
        {
            ReturnedData data = new ReturnedData();

            try
            {
                int pkItemId = NullHelper.Convert<int>(Request["pkItemId"], 0);
                int pkgid = NullHelper.Convert<int>(Request["pkgId"], 0);
                int conNum = NullHelper.Convert<int>(Request["conNum"], 0);
                string pkgName = NullHelper.Convert<string>(Request["pkgName"], "");
                string itemName = NullHelper.Convert<string>(Request["itemName"], "");

                PkgItemsMgm pkgItMgm = new PkgItemsMgm();
                PkgItemVO pkgItem = new PkgItemVO();
                pkgItem.ItemID = pkItemId;
                pkgItem.PackageID = pkgid;
                pkgItem.ConsumeCount = conNum;
                pkgItem.CreatedDate = DateTime.Now;
                pkgItem.CreatorID = Emp.UserName;
                pkgItem.LastModifiedDate = DateTime.Now;
                pkgItem.LastModifierID = Emp.UserName;

Source/UI/Zeta.WisdCar.Online/Views/Package/DetailItems.cshtml
@{
    Layout = null;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title" id="hpkgname">@ViewBag.PkgName</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-th-large"></i>套餐消费项目列表
                    </div>
                    <div class="tools">
                    </div>
                    <a href="javascript:void(0);" class="btn btn-xs blue" onclick="PackageItems.Showdetail()" style="float:right; ">
                        <i class="fa fa-plus"></i> 新增
                    </a>
                </div>
                <div class="portlet-body">
                    <table id="tblPackageItems" class="display" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>消费项目</th>
                                <th>消费次数</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <!-- END PORTLET-->
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">关闭</button>
    <input type="hidden" id="hidPkgId" value="@ViewBag.PkgID" />
</div>
<div id="divPkgItemsDetail" class="modal fade" tabindex="-1" data-width="500" data-backdrop="static" data-keyboard="false">
</div>
<script>
    
    var PackageItems = function () {
        var onPageLoad = function () {
           
            
            initPkgItemsTable();
        };
        var pkgItemsTable = null;
        var initPkgItemsTable = function () {
            //if (pkgItemsTable){
            //    $("#tblPackageItems").DataTable().fnDestroy();
            //    $("#tblPackageItems").DataTable().fnDraw();
            //    return;
            //}
            pkgItemsTable = $("#tblPackageItems").DataTable({
                "processing": false,
                "serverSide": false,
                "ajax": {
                    "type": "post",
                    "data": { id: "@ViewBag.PkgID" },
                    "url": "@Url.Action("GetItemsByPkgId", "Package")",
                    "dataSrc": "",
                    "cache": false
                },
                "columns": [
                    { "data": "ItemName" },
                    { "data": "ConsumeCount" },
                    { "data": "Operation" }
                ],
                "columnDefs": [
                    {
                        "targets": [2],
                        "orderable": false
                    }
                ],
                "order": [[0, "asc"]],
                "bDestroy":true,
                "deferRender": true,
                "scrollX": true,
                "paging": true,
                "ordering": true,
                "info": true,
                //"retrieve": true,    //重复初始化，索引到同一个Datatables实例
                //"pagingType": "full_numbers",
                "pageLength": 10,
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "language": {
                    "emptyTable": "没有数据",
                    "loadingRecords": "加载中...",
                    "processing": "查询中...",
                    "search": "查询: ",
                    "lengthMenu": "显示_MENU_条",
                    "zeroRecords": "没有数据",
                    "paginate": {
                        "previous": "上一页",
                        "next": "下一页",
                        "first": "第一页",
                        "last": "最后一页"
                    },
                    "info": "显示_START_-_END_，共_TOTAL_条记录",
                    "infoEmpty": "0条记录",
                    "infoFiltered": "(查询前有_MAX_条记录)"
                }
            });

            $("#tblPackageItems tbody").on("click", "tr", function () {
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                }
                else {
                    pkgItemsTable.$('tr.selected').removeClass('selected');
                    $(this).addClass('selected');
                }
            });

            $("#tblPackageItems_filter input").addClass("form-control input-medium input-inline");
            $("#tblPackageItems_length select").addClass("form-control input-xsmall input-inline");
        };
        var openDetailModal = function (id) {
            var $modal = $("#divPkgItemsDetail");
            $("body").modalmanager("loading");
            var url = "@Url.Action("PkgItemDetail","Package")?id="+id+"&"+Math.random();  
            $modal.load(url, '', function () {
                $modal.modal();
            });
        };
        return {
            Init: function () {
                onPageLoad();
            },
            Del: function (id, itemName) {

                $.ajax({
                    "type": "post",
                    "url": '@Url.Action("DeletePkgItem", "Package")',
                    "dataType": "json",
                    "data": { id: id,pkgName: '@ViewBag.PkgName', itemName: itemName, },
                    "async": true,
                    "cache": false,
                    "success": function (re) {
                        if (re.Success) {
                            alert(re.Message);
                            
                            initPkgItemsTable();

                        }
                        else {
                            alert(re.Message);
                        }
                    },
                    "error": function () {

                    }
                });
            },
            Showdetail: function () {
                var id = $('#hidPkgId').val();
                openDetailModal(id);
            }
        };
    }();

    $(function () {
        PackageItems.Init();

        
    });
</script>

Source/UI/Zeta.WisdCar.Online/Views/Package/DetailPkg.cshtml

@{
    Layout = null;
}


    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">套餐信息</h4>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PORTLET-->
            <form class="form-horizontal" role="form" width="100%">
                <div class="form-body">

                    <div class="form-group">
                        <label class="col-md-4 control-label" for="PackageAmount">套餐名称:<span class="required">*</span></label>
                        <div class="col-md-4">
                            <input type="text" id="txtPkgName" name="txtPkgName" value="@ViewBag.pkgName" class="form-control" placeholder="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label" for="txtQyName">套餐价格:<span class="required">*</span></label>
                        <div class="col-md-4">
                            <input type="text" id="txtPkgPrice" name="txtPkgPrice" value="@ViewBag.pkgPrice" class="form-control" placeholder="">
                        </div>
                    </div>
                </div>
            </form>

            <!-- END PORTLET-->
        </div>
    </div>
<div class="modal-footer">
    <button type="button" onclick="subForm()" class="btn blue">保存</button>
    <button type="button" class="btn default" data-dismiss="modal">关闭</button>
    <input hidden id="hidId" value="@ViewBag.pkgId" />
</div>
<script type="text/javascript">
    function subForm() {
        var pkgName = $('#txtPkgName').val();
        var pkgPrice = $('#txtPkgPrice').val();
        var id = $('#hidId').val();
        if (!pkgName) {
            alert("套餐名称不能为空");
            return;
        } else if (!pkgPrice) {
            alert("套餐价格不能为空");
            return;
        } else if (isNaN(Number(pkgPrice))) {
            alert("套餐价格必须输入数字");
            return;
        } else if (Number(pkgPrice) <= 0) {
            alert("套餐价格必须大于0");
            return;
        }

        $.ajax({
            "type": "post",
            "url": '@Url.Action("SubPkg", "Package")',
            "dataType": "json",
            "data": {id:id,pkgName:pkgName,pkgPrice:pkgPrice},
            "async": true,
            "cache": false,
            "success": function (re) {
                if (re.Success) {
                    if (id == -1) {
                        alert(re.Message);
                        openDetailModal(re.Data, pkgName);
                    }
                    else {
                        alert(re.Message);
                        closedilog();
                    }
                }
                else {
                    alert(re.Message);
                }
            },
            "error": function () {

            }
        });


        //openDetailModal(1, '内部美容套餐');
    }
    var openDetailModal = function (id, pkgName) {
        var $modal = $("#divPackageItems");
        //$("body").modalmanager("loading");
        var url = "@Url.Action("DetailItems", "Package")?id=" + id + "&pkgName=" + pkgName;
           
        $modal.load(url, '', function () {
            $modal.modal();
        });
    };
</script>

Source/UI/Zeta.WisdCar.Online/Views/Package/Index.cshtml
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            套餐设置 <small>Package</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="@Url.Action("Index", "Dashboard")">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    行销策划
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    套餐设置
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-th-large"></i>套餐列表
                </div>
                <div class="tools">
                </div>
                <a href="javascript:void(0);" onclick="Package.PackgModal()" class="btn btn-xs blue" style="float:right; ">
                    <i class="fa fa-plus"></i> 新增
                </a>
            </div>
            <div class="portlet-body">
                <table id="tblPackage" class="display" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>套餐名称</th>
                            <th>套餐价格</th>
                            <th>消费项目</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <!-- END PORTLET-->
    </div>
</div>
<!-- END PAGE CONTENT-->

<!-- Ajax Modal-->
<div id="divPackageItems" class="modal fade" tabindex="-1" data-width="760" data-backdrop="static" data-keyboard="false">
</div>

<!-- END PAGE CONTENT-->
@section styles{
    <link href="@Url.Content("~/assets/plugins/datatables/css/jquery.dataTables.min.css")" rel="stylesheet" />
}

@section scripts{
    <script src="@Url.Content("~/assets/plugins/datatables/js/jquery.dataTables.min.js")" type="text/javascript"></script>
    <script>
        var Package = function () {
            var onPageLoad = function () {
                initPackageTable();
            };

            var initPackageTable = function () {
                var packageTable = $("#tblPackage").DataTable({
                    "processing": false,
                    "serverSide": false,
                    "ajax": {
                        "type": "post",
                        "url": "@Url.Action("GetAllPackages", "Package")",
                        "dataSrc": "",
                        "cache": false
                    },
                    "columns": [
                        { "data": "PackageName" },
                        { "data": "TotalPriceDesc" },
                        { "data": "DetailOpt" },
                        { "data": "Operation" }
                    ],
                    "columnDefs": [
                        {
                            "targets": [2],
                            "orderable": false
                        },
                        {
                            "targets": [3],
                            "orderable": false
                        }
                    ],
                    "order": [[0, "asc"]],
                    "deferRender": true,
                    "scrollX": true,
                    "paging": true,
                    "ordering": true,
                    "info": true,
                    "retrieve": true,    //重复初始化，索引到同一个Datatables实例
                    //"pagingType": "full_numbers",
                    "pageLength": 10,
                    "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                    "language": {
                        "emptyTable": "没有数据",
                        "loadingRecords": "加载中...",
                        "processing": "查询中...",
                        "search": "查询: ",
                        "lengthMenu": "显示_MENU_条",
                        "zeroRecords": "没有数据",
                        "paginate": {
                            "previous": "上一页",
                            "next": "下一页",
                            "first": "第一页",
                            "last": "最后一页"
                        },
                        "info": "显示_START_-_END_，共_TOTAL_条记录",
                        "infoEmpty": "0条记录",
                        "infoFiltered": "(查询前有_MAX_条记录)"
                    }
                });

                $("#tblPackage tbody").on("click", "tr", function () {
                    if ($(this).hasClass('selected')) {
                        $(this).removeClass('selected');
                    }
                    else {
                        packageTable.$('tr.selected').removeClass('selected');
                        $(this).addClass('selected');
                    }
                });

                $("#tblPackage_filter input").addClass("form-control input-medium input-inline");
                $("#tblPackage_length select").addClass("form-control input-xsmall input-inline");
            };

            var openDetailModal = function (id, pkgName,type) {
                var $modal = $("#divPackageItems");
                $("body").modalmanager("loading");
                var url;
                if (type == 1) {
                    url = "@Url.Action("DetailItems", "Package")?id=" + id + "&pkgName=" + pkgName + "&" + Math.random();
                    url = encodeURI(url);
                } else {
                    url = "@Url.Action("DetailPkg","Package")?id=" + id + "&" + Math.random();
                }
                
                $modal.load(url, '', function () {
                    $modal.modal();
                });
            };

            return {
                Init: function () {
                    $("#sidebar_menu_sell_setting").addClass("active");
                    $("#sidebar_menu_package").addClass("active"); 
                    App.blockUI({ boxed: true });
                    onPageLoad();
                    window.setTimeout(function () {
                        App.unblockUI();
                    }, 1000);
                },
                Edit: function (id) {
                    openDetailModal(id, '', 0);
                },
                Del: function (id) {
                    $.ajax({
                        "type": "post",
                        "url": '@Url.Action("DeletePackage", "Package")',
                        "dataType": "json",
                        "data": { id: id},
                        "async": true,
                        "cache": false,
                        "success": function (re) {
                            if (re.Success) {
                                alert(re.Message);
                                closedilog();
                            }
                            else {
                                alert(re.Message);
                            }
                        },
                        "error": function () {

                        }
                    });
                },
                Detail: function (id, pkgName) {
                    openDetailModal(id, pkgName,1);
                },
                PackgModal: function () {
                    openDetailModal(-1, '', 0);
                }
            };
        }();
        function closedilog() {
            window.location = "@Url.Action("Index","Package")";
        }
        $(function () {
            Package.Init();
        });
    </script>
}

Source/UI/Zeta.WisdCar.Online/Views/Package/PkgItemDetail.cshtml

@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">套餐消费项目信息</h4>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PORTLET-->
        <form class="form-horizontal" role="form" width="100%">
            <div class="form-body">

                <div class="form-group">
                    <label class="col-md-4 control-label" for="PackageAmount">消费项目名称:<span class="required">*</span></label>
                    <div class="col-md-4">
                        @Html.DropDownList("ConItem", null, new { @class = "form-control input-md" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="txtQyName">项目消费次数:<span class="required">*</span></label>
                    <div class="col-md-4">
                        <input type="text" id="txtConNum" name="txtConNum" value="" class="form-control" placeholder="">
                    </div>
                </div>
            </div>
        </form>

        <!-- END PORTLET-->
    </div>
</div>
<div class="modal-footer">
    <button type="button" onclick="subForm()" data-dismiss="modal" class="btn blue">保存</button>
    <button type="button" class="btn default" data-dismiss="modal">关闭</button>
    <input hidden id="hidId" value="-1" />
</div>
<script type="text/javascript">
    function subForm() {
        var pkItemId = $('#ConItem').val();
        var conNum = $('#txtConNum').val();
        var id = $('#hidId').val();
        var itemName = $("#ConItem").find("option:selected").text();
        if (!pkItemId) {
            alert("无效消费项目");
            return;
        }
        if (!conNum) {
            alert("消费次数不能为空");
            return;
        } else if (isNaN(Number(conNum))) {
            alert("消费次数必须输入数字");
            return;
        } else if (Number(conNum) <= 0) {
            alert("消费次数必须大于0");
            return;
        }
        
        $.ajax({
            "type": "post",
            "url": '@Url.Action("AddPkgItem", "Package")',
            "dataType": "json",
            "data": { pkItemId: pkItemId, pkgId: '@ViewBag.PkgID', conNum: conNum, pkgName: '@ViewBag.PkgName', itemName: itemName, },
            "async": true,
            "cache": false,
            "success": function (re) {
                if (re.Success) {           
                    alert(re.Message);
                    PackageItems.Init();
                }
                else {
                    alert(re.Message);
                }
            },
            "error": function () {

            }
        });


        //openDetailModal(1, '内部美容套餐');
    }
    @*var openDetailModal = function (id, pkgName) {
        var $modal = $("#divPackageItems");
        //$("body").modalmanager("loading");
        var url = "@Url.Action("DetailItems", "Package")?id=" + id + "&pkgName=" + pkgName;

        $modal.load(url, '', function () {
            $modal.modal();
        });
    };*@
</script>