Source/UI/Zeta.WisdCar.Online/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Infrastructure.Log;

namespace Zeta.WisdCar.Online.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /TestLayout/
        public ActionResult Index()
        {
            Business.BizMocker.MockLog4Net();

            return View();
        }
    }
}

Source/UI/Zeta.WisdCar.Online/Controllers/RechargeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeta.WisdCar.Business.CustClubCardModule;
using Zeta.WisdCar.Business.Handler;
using Zeta.WisdCar.Business.MarktingPlanModule;
using Zeta.WisdCar.Business.RechargeConsumeModule;
using Zeta.WisdCar.Infrastructure;
using Zeta.WisdCar.Infrastructure.Helper;
using Zeta.WisdCar.Infrastructure.Log;
using Zeta.WisdCar.Model.VO;
using Zeta.WisdCar.Online.App_Start;
using Zeta.WisdCar.Online.Models;

namespace Zeta.WisdCar.Online.Controllers
{
    public class RechargeController : BasePageController
    {
        //
        // GET: /ClubcardRecharge/
        public ActionResult Index()
        {
            int id = NullHelper.Convert<int>(Request["id"], 0);
            CustomerAndCard cuscard = new CustomerAndCard();
            if(id>0)
            {
                IClubCardMgm cardMgm = new ClubCardMgm();
                ClubCardVO card = cardMgm.GetClubCardByID(id);
                ICustomerMgm custMgm = new CustomerMgm();
                CustomerVO cust = custMgm.GetCustomerByID(card.CustomerID);
                cuscard = GetCusAndCardModel(card, cust);
            }
            return View(cuscard);
        }
        public JsonResult SearchCustomerAndCard()
        {
            string mobileno = NullHelper.Convert<string>(Request["MobileNo"], "");
            string cardNo = NullHelper.Convert<string>(Request["CardNo"], "");
            ReturnedData data = new ReturnedData();
            if(!string.IsNullOrEmpty(mobileno)||!string.IsNullOrEmpty(cardNo))
            {
                ICustomerMgm custMgm = new CustomerMgm();
                IClubCardMgm cardMgm = new ClubCardMgm();
                //有缺陷
                if(!string.IsNullOrEmpty(mobileno))
                {
                    CustomerVO cust = custMgm.GetCustomerByMobileNo(mobileno);
                    if(cust!=null)
                    {
                        ClubCardVO card = cardMgm.GetClubCardByCustID(cust.CustomerID);
                        data.Data = GetCusAndCardModel(card, cust);
                        data.Success = true;
                    }
                    else
                    {
                        data.Success = false;
                        data.Message = "当前手机号无用户";
                    }
                    
                }
                else if(!string.IsNullOrEmpty(cardNo))
                {
                    ClubCardVO card = cardMgm.GetClubCardByCardNo(cardNo);
                    if(card!=null)
                    {
                        CustomerVO cust = custMgm.GetCustomerByID(card.CustomerID);
                        data.Data = GetCusAndCardModel(card, cust);
                        data.Success = true;
                    }
                    else
                    {
                        data.Success = false;
                        data.Message = "当前会员卡号无用户";
                    }    
                }  
            }
            else
            {
                data.Success = false;
                data.Message = "请输入会员卡号或用户手机号码";
            }
            return Json(data,JsonRequestBehavior.AllowGet);
        }
        private CustomerAndCard GetCusAndCardModel(ClubCardVO recard, CustomerVO recust)
        {
            if (recard != null && recust != null)
            {
                CustomerAndCard cuandcard = new CustomerAndCard()
                {
                    CustID = recust.CustomerID,
                    CustName = recust.Name,
                    ICNo = recust.ICNo,
                    MobileNo = recust.MobileNO,
                    Birthday = recust.Birthday,
                    CardID = recard.ClubCardID,
                    CardNo = recard.ClubCardNo,
                    CardType = recard.ClubCardTypeID,
                    CardStatu = recard.CardStatus,
                    OpenCardStore = recard.OpenCardStore,
                    SaleMan = recard.SalesMan,
                    SaleTime = recard.SalesTime,
                    ExpireDate = recard.ExpireDate
                };
                cuandcard.CardTypeName = recard.ClubCardTypeName;
                switch(recard.CardStatus)
                {
                    case (int)ClubCardStatus.OpenCard: cuandcard.CardStatuName = "开卡";
                        break;
                    case (int)ClubCardStatus.Expire: cuandcard.CardStatuName = "过期";
                        break;
                    case (int)ClubCardStatus.Froze: cuandcard.CardStatuName = "冻结";
                        break;
                    case (int)ClubCardStatus.LogOff: cuandcard.CardStatuName = "注销";
                        break;
                    case (int)ClubCardStatus.ReportLoss: cuandcard.CardStatuName = "挂失";
                        break;
                }
                return cuandcard;
            }
            return new CustomerAndCard();
        }
        [HttpGet]
        public ActionResult RechargeCash()
        {
            int cardid = NullHelper.Convert<int>(Request["id"],0);
            if(cardid>0)
            {
                IClubCardMgm cardMgm = new ClubCardMgm();
                var card = cardMgm.GetClubCardByID(cardid);
                IClubCardTypeMgm ctypeMgm = new ClubCardTypeMgm();
                var ctype = ctypeMgm.GetCardTypeByID(card.ClubCardTypeID);
                ViewData["name"] = card.CustName;
                ViewData["cno"] = card.ClubCardNo;
                ViewData["ctype"] = card.ClubCardTypeName;
                ViewData["discount"] = ctype.PayDiscount;
            }
            else
            {
                ViewData["name"] = "";
                ViewData["cno"] = "";
                ViewData["ctype"] = "";
                ViewData["discount"] = "";
            }
            
            //recharge.
            return View();
        }
        [HttpPost]
        public JsonResult RechargeCashSub()
        {
            ReturnedData data = new ReturnedData();

            try
            {
                string cardno = NullHelper.Convert<string>(Request["cno"], "");
                decimal rechargeAmount = NullHelper.Convert<decimal>(Request["rechargeAcc"], 0M);
                decimal rechargeDiscount = NullHelper.Convert<decimal>(Request["discount"], 0M);
                IClubCardMgm cardMgm = new ClubCardMgm();
             

                var card = cardMgm.GetClubCardByCardNo(cardno);
                RechargeVO recharge = new RechargeVO();
                recharge.ClubCardID = card.ClubCardID;
                recharge.ClubCardNo = card.ClubCardNo;
                recharge.ActualRechargeAmount = rechargeAmount;
                recharge.CustID = card.CustomerID;
                recharge.CustName = card.CustName;
                recharge.DiscountRate = rechargeDiscount;
                if (rechargeDiscount == 0)
                {
                    rechargeDiscount = 1;
                }
                recharge.PlatformRechargeAmount =Math.Round(rechargeAmount/ rechargeDiscount,2);
                recharge.RechargeDate = DateTime.Now;
                recharge.RechargeStore = Emp.StroeName;
                recharge.OriginalStore = card.OpenCardStore;
                recharge.PayType = (int)PayType.Cash;
                recharge.LastModifierID = Emp.UserName;
                recharge.LastModifiedDate = DateTime.Now;
                recharge.CreatedDate = DateTime.Now;
                recharge.CreatorID = Emp.UserName;
                recharge.DiscountInfo = "会员现金折扣";
                recharge.ClubCardPackageID = "";
                recharge.RechargeType = (int)RechargeType.ClubCash;
                recharge.RechargeSerialNo = SerialNoGenerator.GenRechargeSerialNo(Emp.StoreId);
                recharge.SalesMan = card.SalesMan;

                IRechargeMgm rechargeMgm = new RechargeMgm();
                rechargeMgm.RechargeCash(recharge);
                data.Success = true;
                Session.Add("recharge", recharge);
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Error = ex.ToString();
                data.Message = "充值失败";
                
            }
            
            return Json(data,JsonRequestBehavior.AllowGet);
        }
        public ActionResult RechargeSuccess()
        {
            RechargeVO recharge = new RechargeVO();
            if(Session["recharge"]!=null)
            {
                recharge = Session["recharge"] as RechargeVO;
                Session.Remove("recharge");
            }

            return View(recharge);
        }
        public ActionResult RechargePkg()
        {
            
            int cardid = NullHelper.Convert<int>(Request["id"], 0);
            ClubCardMgm cardMgm = new ClubCardMgm();
            var card = cardMgm.GetClubCardByID(cardid);
            ViewData["PkgBag"] = GetddlList(DDLlist.Pkg, false, null, null);
            ViewBag.Data = card;
            return View();
        }
        public JsonResult GetPkgItems()
        {
            ReturnedData data = new ReturnedData();
            try
            {
                int pkgId = NullHelper.Convert<int>(Request["id"], -1);
                PkgItemsMgm pkgMgm = new PkgItemsMgm();
                PackageMgm pkMgm = new PackageMgm();

                var pkg = pkMgm.GetPackageByID(pkgId);
                var pkgitem = pkgMgm.GetItemsByPkgID(pkgId);
                data.Success = true;
                data.Message = pkg.TotalPrice.ToString();
                data.Data = pkgitem;
            }
            catch (Exception ex)
            {
                data.Success = false;
                data.Message = "系统错误，请联系维护人员";
                data.Error = ex.ToString();
                LogHandler.Error(ex.Message.ToString());
            }
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult RechargePkgSub()
        {

Source/UI/Zeta.WisdCar.Online/Views/Recharge/Index.cshtml
@model Zeta.WisdCar.Online.Models.CustomerAndCard
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            会员充值 <small>Clubcard Recharge</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="@Url.Action("Index", "Dashboard")">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    充值消费
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    会员充值
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>充值管理
        </div>
        <!-- <div class="tools">
        </div>
        <a href="#" class="btn btn-xs blue" style="float:right; ">
            <i class="fa fa-plus"></i> 新增
        </a> -->
    </div>


    <div class="portlet-body">

        <div class="portlet box" style=" border:1px solid #bde9f1;">
            <div class="portlet-body">
                <form class="form-horizontal">

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="txtQyCardNo">会员卡号</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.CardNo, new { @class = "form-control" })
                            @*<input type="text" id="txtQyCardNo" name="CardNo" class="form-control" placeholder="">*@
                        </div>
                        <label class="col-md-2 control-label" for="txtQyMobileNo">手机号码</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.MobileNo, new { @class = "form-control" })
                            @*<input type="text" id="txtQyMobileNo" name="MobileNo" class="form-control" placeholder="">*@
                        </div>
                        <div class="col-md-2">

                        </div>
                        <div class="col-md-2">
                            <a id="btnQy" href="javacript:void(0);" onclick="searchModel(); return false;" class="btn btn-md blue">
                                <i class="fa fa-search"></i> 查询
                            </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">明细信息</h3>
            </div>
            <div class="panel-body">
                <div class="portlet box" style="margin-bottom:10px; border:1px solid #bde9f1;">
                    <div class="portlet-body">
                        <form class="form-horizontal">

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="txtQyName">姓名：</label>
                                <div class="col-md-4">
                                    
                                    <label class="control-label" id="lblName">@Model.CustName</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" >手机号码：</label>
                                <div class="col-md-4">
                                   
                                    <label class="control-label" id="lblMno">@Model.MobileNo</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="txtQyICNo">身份证号：</label>
                                <div class="col-md-4">
                                   
                                    <label class="control-label" id="lblIcno">@Model.ICNo</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="txtQyCardNo">会员卡号：</label>
                                <div class="col-md-4">
                                   
                                    <label class="control-label" id="lblCardno">@Model.CardNo</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="ddlCardType">会员卡类型：</label>
                                <div class="col-md-4">
                                   
                                    <label class="control-label" id="lblCardtname">@Model.CardTypeName</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="ddlCardState">会员卡状态：</label>
                                <div class="col-md-4">
                                    <label class="control-label" id="lblCardstatu">@Model.CardStatuName</label>
                                </div>
                            </div>
                            @Html.HiddenFor(m => m.CardID)
                            @Html.HiddenFor(m=>m.CardStatu)
                            @*<div class="form-group">
                                <label class="col-md-2 control-label" for="txtQydate">截至日期：</label>
                                <div class="col-md-4">
                                    <label class="col-md-2 control-label" for="ddlCardState">20150831</label>
                                </div>
                            </div>*@

                            <div class="form-group">
                                <label class="col-md-1 control-label"></label>
                                <div class="col-md-1">
                                    <a id="btnQy" href="javacript:void(0);" onclick="recharge(0); return false;" class="btn btn-md blue"> 充值现金 </a>
                                </div>
                                <div class="col-md-1"></div>
                                <div class="col-md-1"> <a id="btnQy" href="javacript:void(0);" onclick="recharge(1); return false;" class="btn btn-md blue"> 购买套餐 </a></div>
                                <div class="col-md-1"></div>
                                <div class="col-md-2"></div>
                                <div class="col-md-2"></div>
                                <div class="col-md-2"></div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- END PAGE CONTENT-->
@section scripts{
    <script>
        function recharge(type) {
            var url;
            var cardid = $('#CardID').val();
            var cardstatu = $('#CardStatu').val();
            
            if (cardid==0) {
                return;
            }
            if(cardstatu!=0){
                alert("当前会员卡状态不允许充值");
                return;
            }
            if (type==0) {
                url = "@Url.Action("RechargeCash","Recharge")"+'?id='+cardid;
            } else {
                url = "@Url.Action("RechargePkg","Recharge")"+'?id='+cardid;
            }
            if (url) {
                window.location.href = url;
            }
        }
        function searchModel()
        {
            var mno = $('#MobileNo').val();
            var cardno = $('#CardNo').val();
            if (!mno && !cardno)
            {
                alert("请输入会员卡号或客户手机号以便查询");
                return;
            }
            //SearchCustomerAndCard
            $.ajax({
                "type": "post",
                "url": "@Url.Action("SearchCustomerAndCard", "Recharge")",
                        "dataType": "json",
                        "data": { MobileNo: mno,CardNo:cardno },
                        "async":true,
                        "cache": false,
                        "success": function (re) {
                            if (re.Success)
                            {
                                $('#lblName').html(re.Data.CustName);
                                $('#lblMno').html(re.Data.MobileNo);
                                $('#lblIcno').html(re.Data.ICNo);
                                $('#lblCardno').html(re.Data.CardNo);
                                $('#lblCardtname').html(re.Data.CardTypeName);
                                $('#lblCardstatu').html(re.Data.CardStatuName);
                                $('#CardID').val(re.Data.CardID);
                                $('#CardStatu').val(re.Data.CardStatu);
                            }
                            else
                            {
                                alert(re.Message);
                            }
                        }, 
                        "error": function () {
                            alert(re.Error);
                        }
            });
        }
        var ClubcardRecharge = function () {
            var onPageLoad = function () {

            };

            return {
                Init: function () {
                    $("#sidebar_menu_recharge_consume").addClass("active");
                    $("#sidebar_menu_clubcard_recharge").addClass("active");
                    App.blockUI({ boxed: true });
                    onPageLoad();
                    window.setTimeout(function () {
                        App.unblockUI();
                    }, 1000);
                }
            };
        }();

        $(function () {
            ClubcardRecharge.Init();
        });
    </script>
}

Source/UI/Zeta.WisdCar.Online/Views/Recharge/RechargePkg.cshtml

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            购买套餐 <small>Purchase packages</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">

            <li>
                <i class="fa fa-home"></i>
                <a href="index.html">
                    首页
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    充值消费
                </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">
                    购买套餐
                </a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>购买套餐
        </div>
        <!-- <div class="tools">
        </div>
        <a href="#" class="btn btn-xs blue" style="float:right; ">
            <i class="fa fa-plus"></i> 新增
        </a> -->
    </div>


    <div class="portlet-body">

        <div class="portlet box" style=" border:1px solid #bde9f1;">
            <div class="portlet-body">
                <form class="form-horizontal">

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="PackageName">套餐名称</label>
                        <div class="col-md-2">
                            @Html.DropDownList("PkgBag", null, new { @class = "form-control input-md" })
                        </div>

                        <div class="col-md-2">

                        </div>
                        @*<div class="col-md-2">
                            <a id="btnQy" href="javacript:void(0);" class="btn btn-md blue">
                                <i class="fa fa-search"></i> 查询
                            </a>
                        </div>*@
                    </div>

                </form>

                <div class="margin-top-10 margin-bottom-10 clearfix">
                    <table id="tblPkgItem" class="table table-bordered table-striped">
                        <tr>
                            <td>
                                消费项目名称
                            </td>
                            <td>
                                消费次数
                            </td>
                        </tr>
                    </table>
                </div>

            </div>
        </div>

        <form class="form-horizontal">

            <div class="form-group">
                <label class="col-md-2 control-label" for="txtQyName">客户姓名：</label>
                <div class="col-md-4">
                    <label class="control-label">@ViewBag.Data.CustName</label>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="txtQyCardNo">会员卡号：</label>
                <div class="col-md-4">
                    <label id="lblCno" class="control-label">@ViewBag.Data.ClubCardNo</label>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="ddlCardType">会员卡类型：</label>
                <div class="col-md-4">
                    <label class="control-label">@ViewBag.Data.ClubCardTypeName</label>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-2 control-label" for="TotalPackage">套餐总价：</label>
                <div class="col-md-4">
                    <label id="lblPkgPrice" class="control-label">0.00</label>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="DiscountPackages">套餐折扣：</label>
                <div class="col-md-4">
                    <label id="lblDisCount" class="control-label">@ViewBag.Data.PackageDiscount</label>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="RealincomeAmount">实收金额：</label>
                <div class="col-md-4">
                    <label class="control-label" id="lblPkgRecAmount">0.00</label>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-2 control-label" for="PaymentType">支付方式:</label>
                <div class="col-md-4">
                    <div>
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#home" onclick="payType('cash')" aria-controls="home" role="tab" data-toggle="tab">现金</a></li>
                            <li role="presentation"><a href="#profile" aria-controls="profile" onclick="payType('bankcard')" role="tab" data-toggle="tab">其他</a></li>
                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                支付现金，进行充值。点击确认支付直接交易，请仔细查看消费信息。
                            </div>
                            <div role="tabpanel" class="tab-pane" id="profile">...</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-1" id="ajax-demo" data-toggle="modal">
                    <a id="btnQy" href="javacript:void(0);" onclick="payForm()" class="btn btn-md blue"> 确认支付 </a>
                </div>
            </div>

        </form>
    </div>
</div>
@section styles{
    <link href="@Url.Content("~/assets/plugins/datatables/css/jquery.dataTables.min.css")" rel="stylesheet" />
}
@section scripts{
    <script src="@Url.Content("~/assets/plugins/datatables/js/jquery.dataTables.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
        
        //function payType(t) {
        //    if (t == 'cash') {
        //        $('#lblPaytype').html('现金');
        //        $('#hidPaytype').val(t);
        //    } else if (t == 'bankcard') {
        //        $('#lblPaytype').html('银行卡');
        //        $('#hidPaytype').val(t);
        //    }
        //}
        function payForm() {
            //提交充值信息
            var cno = $('#lblCno').text();
            var pkgId =$("#PkgBag").val();
            var discount = $('#lblDisCount').text();
            var rechamount =$("#lblPkgRecAmount").text();
            var pkgPrice = $("#lblPkgPrice").text();
            var paytype = $('#hidPaytype').val();

            $.ajax({
                "type": "post",
                "url": "@Url.Action("RechargePkgSub", "Recharge")",
                "dataType": "json",
                "data": { cardNo: cno, pkgId: pkgId, disCount: discount, rechAmount: rechamount, pkgPrice: pkgPrice },
                "async": true,
                "cache": false,
                "success": function (re) {
                    if (re.Success) {
                        window.location.href = "@Url.Action("RechargePkgSuccess","Recharge")"
                    } else {
                        alert(re.Message);
                    }
                },
                "error": function () {
                    alert(re.Error);
                }
            })
        }
        var RechargePkg = function () {
            var ddlSelect = function () {
                $("#PkgBag").change(function () {
                    var selectVal = $("#PkgBag").val();
                    if(selectVal>0){
                        getPkgItems(selectVal);
                    }
               })
            }
            var getPkgItems = function (id) {
                $.ajax({
                    "type": "post",
                    "url": "@Url.Action("GetPkgItems", "Recharge")",
                    "dataType": "json",
                    "data": { id:id },
                    "async":true,
                    "cache": false,
                    "success": function (re) {
                        if (re) {
                            var reobj = re.Data;
                            var tbl = "<tr><td>消费项目名称</td><td>消费次数</td></tr>";
                            $.each(reobj, function (n,v) {
                                //alert(v.ItemName);
                                //alert(v.ConsumeCount);
                                tbl = tbl + "<tr><td>" + v.ItemName + "</td><td>" + v.ConsumeCount + "</td></tr>";

                            })
                            $("#lblPkgPrice").text(re.Message);
                            var reciveAmount=0.00;
                            var discount = $("#lblDisCount").text();
                            if (Number(discount) > 0) {
                                reciveAmount = Number(re.Message) * Number(discount);
                            } else {
                                reciveAmount = re.Message;
                            }
                                
                            $("#lblPkgRecAmount").text(reciveAmount);
                            $("#tblPkgItem").html(tbl);
                        } else {
                            alert(re.Message);
                        }
                    },
                    "error":function(){

                    }
                });
            }
            return {
                Init: function (a) {
                    $("#sidebar_menu_recharge_consume").addClass("active");
                    $("#sidebar_menu_clubcard_recharge").addClass("active");
                    App.blockUI({ boxed: true });
                    ddlSelect();
                    getPkgItems($("#PkgBag").val());
                    window.setTimeout(function () {
                        App.unblockUI();
                    }, 1000);
                }
            }
        }();
        $(function () {
            RechargePkg.Init();
        })
    </script>
}
